name: Update TryHackMe Static Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download static TryHackMe badge
        run: |
          mkdir -p assets
          curl -o assets/tryhackme.png \
          https://tryhackme-badges.s3.amazonaws.com/KernelCurly.png

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/tryhackme.png
          git commit -m "Update TryHackMe static badge" || exit 0
          git push
